### ISSUE TITLE
4 Positives on VirusTotal

### ISSUE THREAD

**Issue by Gravity2106** [luckas72/Anki_Addon_Exporter#5]
SecureAge -Malicious

Sophos - Generic ML PUA (PUA)

Trellix (FireEye) - Generic.mg.bb712fab8c4aae5e

Zillya - Trojan.Badur.Win32.34042

https://www.virustotal.com/gui/file/14815df3057412c8acd4c67dc92fc3daf874f516d3add2f982ae60811caa1181

Could be false positives

**Comment by luq7** [comment]
Lol, Thank you for pointing that out, the source code is right there. If you do not have faith in the code, you could simply go through it. It won't take long.
